### ISSUE TITLE
Support for multiline python comment

### ISSUE THREAD

**Issue by danielfleischer** [alphapapa/obvious.el#1]
Great package! would you consider supporting multi-line python comments? of the form 

```python
def func():
    """
    This is a 
    multiline
    comment
    """
    return 42
```

**Comment by alphapapa** [comment]
Hi Daniel,

Thanks, I'm glad it's useful to you.

I'm not sure what you mean, because the example you gave is a string, not a comment.  Hiding large, multiline comments in Python or similar languages isn't a bad idea, though...

**Comment by danielfleischer** [comment]
Right, it's not a comment, it's a docstring. I'm working on some code with huge class docstrings; I want to use folding and the ability to hide these to reduce the noise and have a nice code skeleton. I can try to add this myself.

**Comment by alphapapa** [comment]
Yeah, that seems like a good idea.  I'm not sure if it should be done in this package, but I'm willing to consider it, depending on the changes required.

**Comment by danielfleischer** [comment]
I found [elpy folding for docstrings](https://elpy.readthedocs.io/en/latest/ide.html#command-elpy-folding-toggle-docstrings) so we might close this and let interested people use elpy's code.

**Comment by alphapapa** [comment]
Sounds good.  Thanks.
